# This file makes it easier to run bibref (the command line version in web) in a Docker virtualization.

# How to use this file:
# 1. On Ubuntu Linux, install the package **docker.io**.
# 2. Build the image by entering `sudo docker build -f Dockerfile.web .`.
#    You will get an image ID at the end of the process.
# 3. Start the web server and allow a network connection to it by issuing `sudo docker run -d -p 8080:80 ID`
#    where ID stands for the obtained image ID in step 2.
#    You will get a container identifier CID as output.
# 4. Open your favorite web browser and open the page **http://localhost:8080/index-jt-dt.html**. This starts the program.
# 5. When finished, stop the web server by using the command `sudo docker kill CID`
#    where CID stands for the obtained container identifier in step 3.


# Install prerequisites:
FROM ubuntu:24.04
SHELL ["/bin/bash", "-c"]
RUN apt-get update && \
    apt-get -y install python3 xz-utils subversion git nginx \
        libsword-common libsword-dev build-essential cmake \
        libreadline-dev libboost-dev libboost-filesystem-dev bison flex pkgconf unzip
RUN git clone https://github.com/emscripten-core/emsdk.git
WORKDIR emsdk
RUN ./emsdk install 4.0.3
RUN ./emsdk activate 4.0.3
WORKDIR ..

# Build SWORD:
RUN until svn co https://crosswire.org/svn/sword/trunk/ sword; do [ -d sword ] && (cd sword && svn cleanup && svn update); sleep 5; done
WORKDIR sword
RUN mkdir build
WORKDIR build
RUN . ../../emsdk/emsdk_env.sh && \
    emcmake cmake -DSWORD_BUILD_UTILS=No -DSWORD_BUILD_EXAMPLES=No -DLIBSWORD_LIBRARY_TYPE=Static -DCMAKE_CXX_FLAGS=-sUSE_ZLIB -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ..
RUN yes | make sword_static
RUN make install
WORKDIR ../..

# Build bibref (cli):
RUN git clone https://github.com/kovzol/bibref
WORKDIR bibref
RUN mkdir build
WORKDIR build
RUN cmake .. && make && make install || true

# Create the addbooks-cache:
RUN bibref -a

# Build bibref (cli-web):
WORKDIR ..
RUN mkdir build-wasm
WORKDIR build-wasm
RUN . ../../emsdk/emsdk_env.sh && \
    emcmake cmake .. -DBIBREF_ADDBOOKS_CACHE_FOLDER=../build/bibref-addbooks-cache
RUN yes | make
RUN make install

# Set up web server:
EXPOSE 80
RUN cp html-output/* /var/www/html

# Allow connection to the web server running in docker:
CMD ["nginx", "-g", "daemon off;"]
