name: bibref
base: core20
version: '2026-03-25'
summary: A tool that helps discovering internal references in the Bible
icon: logo-Psalm40-192.png
description: |
  bibref aims at finding citations of the Septuagint
  in the Greek New Testament in a mechanical way.

grade: stable
confinement: strict

apps:
  bibref:
    command: usr/local/bin/bibref
    environment:
      SWORD_PATH: $SNAP/root/.sword
      LC_ALL: C.UTF-8
      FONTCONFIG_PATH: $SNAP/etc/fonts
    plugs:
      - home

parts:
  bibref:
    build-packages: [cmake, libsword-utils, libsword-common, libsword-dev, build-essential, libboost-dev, libboost-filesystem-dev, libreadline-dev, libgraphviz-dev, libfribidi-dev, pkg-config, unzip, bison, flex, graphviz]
    source: https://github.com/kovzol/bibref.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_BUILD_TYPE=Debug -DWITH_FRIBIDI=ON
    stage-packages: [libsword-1.8.1, libboost-filesystem1.71.0, libgvc6, graphviz, libfribidi0, fontconfig, fontconfig-config, fonts-dejavu-core]
    override-build: |
      snapcraftctl build
      dot -c
      cp /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/graphviz/config6a $SNAPCRAFT_PART_INSTALL/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/graphviz
  sword-modules:
    plugin: nil
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/root
      cp -a ~/.sword $SNAPCRAFT_PART_INSTALL/root
