#!/bin/bash

# Change SBLGNT to StatResGNT in all files in the input folder $1.

if [ "$1" = "" ]; then
 echo "Usage: $0 <input folder>"
 exit 1
 fi

find $1 -name '*.brst' | while read i; do
 echo $i
 cat $i | sed s/SBLGNT/StatResGNT/g > $i.tmp1
 ../pbrst-cli -r -D -C -U $i.tmp1 > $i.tmp2
 target=`readlink -f $i`
 mv $i.tmp2 $target
 rm $i.tmp1
 done
