#!/bin/bash

# This test assumes that pbrst-cli has already been compiled.
# It creates an HTML file with embedded SVG images.

HTML=graphviz.html
echo "<html><body><center>" > $HTML

FILES=`ls -1 *.brst`
F_NO=`ls -1 *.brst | wc -l`
n=0
for i in $FILES; do
 n=$((n+1))
 echo -n -e "\r$i ($n/$F_NO)\033[0K"
 ../pbrst-cli -g $i > $i.dot
 test -s $i.dot && {
  dot -Tsvg $i.dot > $i.svg
  echo "<img src=$i.svg><br>" >> $HTML
 }
 done
echo -e "\rDone.\033[0K"

echo "</center></body></html>" >> $HTML
