#!/bin/bash

# This test assumes that pbrst-cli has already been compiled.
# It creates an HTML file with embedded SVG images.

FOLDER=$1
if [ "$FOLDER" = "" ]; then
 FOLDER=.
 fi

HTML=graphviz.html
HTML_SVG=graphviz-svg.html
HTML_BRST_SVG=graphviz-brst-svg.html

echo "<html><body><center>" > $HTML
echo "<html><body><center>" > $HTML_SVG
echo "<html>
<link rel=\"stylesheet\" type=\"text/css\" href=\"highlight.css\">
<body>" > $HTML_BRST_SVG

FILES=`ls -1 $FOLDER/*.brst`
F_NO=`ls -1 $FOLDER/*.brst | wc -l`
n=0
for i in $FILES; do
 n=$((n+1))
 echo -n -e "\r$i ($n/$F_NO)\033[0K"
 ../pbrst-cli -g $i > $i.dot
 test -s $i.dot && {
  dot -Tsvg $i.dot > $i.svg
  echo "<img src=$i.svg><br>" >> $HTML

  tail -n +7 $i.svg >> $HTML_SVG # remove head
  echo "<br>" >> $HTML_SVG

  highlight --config-file=../../docs/common/brst.lang $i -u utf8 -o $i.html
  cat $i.html | tail -n +9 | head -n -3 >> $HTML_BRST_SVG
  echo "<center>" >> $HTML_BRST_SVG
  tail -n +7 $i.svg >> $HTML_BRST_SVG
  echo "</center><hr>" >> $HTML_BRST_SVG
 }
 done
echo -e "\rDone.\033[0K"

echo "</center></body></html>" >> $HTML
echo "</center></body></html>" >> $HTML_SVG
echo "</body></html>" >> $HTML_BRST_SVG
