#!/bin/bash

# This script creates a folder for the Windows version.
# Usage: ./create-windows-folder <build-dir>
# where build-dir is the executable that has already been built.

# Mandatory checks...

if [ "$1" = "" ]; then
 echo "Usage: $0 <build-dir>"
 exit 1
 fi

test -x $1/bibref-qt.exe || {
 echo "Build bibref-qt.exe first."
 exit 2
 }

BIBREF_VERSION=`cat main.h | grep BIBREF_VERSION | awk '{print $3}' | tr -d \"`
FOLDER=bibref-qt-$BIBREF_VERSION
test -d $FOLDER && {
 echo "Folder $FOLDER exists. Remove it first."
 exit 3
 }

test -d $1/bibref-addbooks-cache || {
 echo "Create the addbooks cache by running bibref-qt.exe and select File > Add books..."
 exit 4
 }

# Create the output folder, put the .exe and .ico files there...

mkdir $FOLDER
cp $1/bibref-qt.exe $FOLDER
cp ../bibref.ico $FOLDER

# Copy the pre-created cache...

cp -a $1/bibref-addbooks-cache $FOLDER

# Copy the DLLs...

for f in Qt6Core.dll Qt6Gui.dll Qt6Widgets.dll libb2-1.dll libboost_filesystem-mt.dll \
 libbrotlicommon.dll libbrotlidec.dll libbz2-1.dll libdouble-conversion.dll \
 libfreetype-6.dll libgcc_s_seh-1.dll libglib-2.0-0.dll libgraphite2.dll \
 libharfbuzz-0.dll libiconv-2.dll libicudt72.dll libicuin72.dll libicuuc72.dll\
 libintl-8.dll liblzma-5.dll libmd4c.dll libpcre2-16-0.dll libpcre2-8-0.dll \
 libpng16-16.dll libreadline8.dll libstdc++-6.dll libtermcap-0.dll libwinpthread-1.dll zlib1.dll; do
 DLL_FULLPATH=`which $f`
 cp $DLL_FULLPATH $FOLDER
 done

# Put the application log and the translations there...

mkdir -p $FOLDER/share/bibref-qt
cp ../logo-Psalm40-192.png $FOLDER/share/bibref-qt
cp *.qm $FOLDER/share/bibref-qt

# Create the SWORD databases...

unzip -d $FOLDER ../sword-lxx-sblgnt-statresgnt-kjv-fallback.zip
mv $FOLDER/.sword $FOLDER/sword

# Create the startup script...

echo "set SWORD_PATH=%homedrive%%homepath%\.sword
if not exist \"%SWORD_PATH%\" mkdir \"%SWORD_PATH%\" & xcopy /q /e sword\\*.\* \"%SWORD_PATH%\"
start \"\" bibref-qt.exe" > $FOLDER/start.bat

# Create additional Qt related settings...

for d in styles platforms; do
 cp -a $MSYSTEM_PREFIX/share/qt6/plugins/$d $FOLDER
 done
