#!/bin/bash

# This script creates a folder for the Windows version.
# Usage: ./create-windows-folder <build-dir> [-f]
# where build-dir is the folder where the executable has already been built,
# and the option -f can force operation even if no addbooks cache exists yet.

# Mandatory checks...

if [ "$MSYSTEM" != "MINGW64" ]; then
 echo "Please run this script in a MSYS2/MINGW64 environment"
 exit 5
 fi

which unzip >/dev/null || {
 echo "Please install unzip first"
 exit 6
 }

which ntldd >/dev/null || {
 echo "Please install ntldd before running this tool"
 exit 7
 }

if [ "$1" = "" ]; then
 echo "Usage: $0 <build-dir> [-f]"
 echo "where -f can be used if the build system does not provide a fully working bibref yet"
 exit 1
 fi

test -x $1/bibref-qt.exe || {
 echo "Build bibref-qt.exe first."
 exit 2
 }

BIBREF_VERSION=`cat main.h | grep BIBREF_VERSION | awk '{print $3}' | tr -d \"`
FOLDER=bibref-qt-$BIBREF_VERSION
test -d $FOLDER && {
 echo "Folder $FOLDER exists. Remove it first."
 exit 3
 }

test -d $1/bibref-addbooks-cache || {
 if [ "$2" != "-f" ]; then
  echo "Create the addbooks cache by running bibref-qt.exe and select File > Add books"
  exit 4
 else
  echo "There is no addbooks cache yet, will not be used in this run"
  fi
 }

# Create the output folder, put the .exe and .ico files there...

mkdir $FOLDER
cp $1/bibref-qt.exe $FOLDER
cp ../bibref.ico $FOLDER

# Copy the pre-created cache...

if [ "$2" != "-f" ]; then
 cp -a $1/bibref-addbooks-cache $FOLDER
 fi

# Copy the DLLs...

ntldd -R $FOLDER/bibref-qt.exe | grep mingw64 | awk '{print "/mingw64/bin/" $1}' | xargs cp -t $FOLDER

# Put the application logo and the translations there...

mkdir -p $FOLDER/share/bibref-qt
cp ../logo-Psalm40-192.png $FOLDER/share/bibref-qt
cp *.qm $FOLDER/share/bibref-qt

# Create the SWORD databases...

unzip -d $FOLDER ../sword-lxx-sblgnt-statresgnt-kjv-fallback.zip
mv $FOLDER/.sword $FOLDER/sword

# Create the startup script...

echo "set SWORD_PATH=%homedrive%%homepath%\.sword
if not exist \"%SWORD_PATH%\" mkdir \"%SWORD_PATH%\" & xcopy /q /e sword \"%SWORD_PATH%\"
start \"\" bibref-qt.exe" > $FOLDER/start.bat

# Create additional Qt related settings...

for d in styles platforms; do
 cp -a $MSYSTEM_PREFIX/share/qt6/plugins/$d $FOLDER
 done

# Create statements folder...
mkdir $FOLDER/statements
cp -a ../statements/SBLGNT/* $FOLDER/statements
rm -fr $FOLDER/statements/all # don't need to have the copies
