#!/bin/sh

# Usage: ./deploy-mac [build-dir] [codesign]
# where build-dir is the folder where the executable has already been built (by default, "build/")
# and codesign is the input for performing an optional code signing.

BUILD_DIR="$1"

if [ "$BUILD_DIR" = "" ]; then
 BUILD_DIR="build/"
 fi

MACDEPLOYQT=$(command -v macdeployqt)
if [ ! -x "$MACDEPLOYQT" ]; then
    echo "macdeployqt is not in path."
    exit 1
fi

test -d "$BUILD_DIR/bibref-qt.app/" || {
    echo "Missing $BUILD_DIR/bibref-qt.app/. Build bibref-qt first."
    exit 2
    }

test -d bin || {
    mkdir bin
    cp -R $BUILD_DIR/bibref-qt.app bin
    }

mkdir -p "bin/bibref-qt.app/Contents/Resources/statements/"
cp ../statements/SBLGNT/*/* bin/bibref-qt.app/Contents/Resources/statements/
rm -fr bin/bibref-qt.app/Contents/Resources/statements/all
if [ -z "$2" ]; then
    $MACDEPLOYQT bin/bibref-qt.app -dmg
else
    $MACDEPLOYQT bin/bibref-qt.app -dmg -codesign="$2"
fi
