std::vector<std::string> descriptions = {
"E1 The length, given as the second parameter in parenthesis, describes a different quantity than the first parameter (which is an interval). Auto-resolution will change the length according to the interval length.",
"E2 The Bible passage and the raw position (given in parenthesis) are controversial, they do not define the same text. Auto-resolution will fix the raw position to match the passage.",
"E3 The Bible passage and the raw position (given in parenthesis) do not define the same text, since the Bible passage is defined incorrectly.",
"E4 There is an Old Testament book given among the fragments that was not introduced in the headline.",
"E5 The Bible passage defined in the introduction does not match to the a-y form defined later, they differ.",
"E6 A textual expression was mentioned in the explanation of an introductory text, but it cannot be found in the introduction.",
"E7 The Bible passage defined in the New Testament fragment does not match to the a-y form defined later, they differ.",
"E8 The Bible passage defined in the Old Testament fragment does not match to the a-y form defined later, they differ.",
"E9 The Jaccard difference given between two fragments is given incorrectly. Auto-resolution will change the number to the correct value.",
"E10 It is stated that the Old Testament passage is unique, but in reality it is not.",
"E11 Percentual rate of coverage of the New Testament passage was computed incorrectly. Auto-resolution will change the number to the correct value.",
"E12 It is not allowed to define passages that overlap. Here, an introductory passage from the New Testament overlaps a fragment interval.",
"E13 It is not allowed to define passages that overlap. Here, two introductory passages from the New Testament overlap each other.",
"E14 The New Testament headline passage must cover all non-introductory fragments.",
"E15 The Old Testament headline passage must contain at least one fragment from the specified book.",
"E16 The Old Testament headline passage must cover all non-introductory fragments.",
"E17 It is not allowed to define passages that overlap. Here, two passages from the Old Testament overlap each other.",
"E18 The Bible passage is defined incorrectly.",
"E19 The raw position (given in parenthesis) is defined incorrectly.",
"W1 You may want to add the length of the interval as a second parameter in the parenthesis to display a clear correspondence of the parts of the text.",
"W2 The passage in the Old Testament is unique. You may want to mention this fact to highlight this property of the text.",
"W3 The New Testament headline covers a wider text interval than the union of the fragments. If the content is longer than the fragments, then this is not a problem, but you may want to check if the headline should be shortened.",
"W4 The Old Testament headline covers a wider text interval than the union of the fragments. If the content is longer than the fragments, then this is not a problem, but you may want to check if the headline should be shortened."
};
