name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: add custom deb repository
      uses: myci-actions/add-deb-repo@4
      with:
#        repo: deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/
#        repo-name: cran40
#        keys: E298A3A825C0D65DFD57CBB651716619E084DAB9
#        key-server: keyserver.ubuntu.com
        repo: deb [trusted=yes] http://debian.ethz.ch/debian stable main contrib non-free
        repo-name: debian
    - name: prerequisites
      run: >-
         sudo apt update --allow-unauthenticated --allow-insecure-repositories &&
         sudo apt install libsword-common libsword-dev git cmake build-essential libreadline-dev libboost-dev \
              sqlite3 python3 python3-pexpect \
              texlive-latex-recommended texlive-latex-extra texlive-science texlive-lang-european texlive-lang-german \
              r-base-core r-cran-sm
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: db-full
      run: cd docs/common && make
#    - name: db-incomplete
#      run: cd docs/common && make authors.pdf manual_nt_length.pdf getrefs.pdf Romans-getrefs.png
    - name: doc-hu
      run: cd docs/hu && make
#    - name: selftest
#      run: cd docs/common && ./selftest.py
