name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: >-
         sudo apt update --allow-unauthenticated --allow-insecure-repositories &&
         sudo apt install libsword-common libsword-dev git cmake build-essential libreadline-dev libboost-dev libboost-filesystem-dev\
              sqlite3 python3 python3-pexpect \
              texlive-latex-recommended texlive-latex-extra texlive-science texlive-lang-european texlive-lang-german \
              r-base-core pdf2svg
    - name: prerequisites2
      run: >-
         wget http://http.us.debian.org/debian/pool/main/s/sm/r-cran-sm_2.2-5.6-1+b2_amd64.deb &&
         sudo dpkg -i r-cran-sm_2.2-5.6-1+b2_amd64.deb
    - name: make-native
      run: |
        mkdir build
        cd build
        cmake ..
        make
    - name: install-emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install 2.0.22
        ./emsdk activate 2.0.22
    - name: make-sword-wasm
      run: |
        . emsdk/emsdk_env.sh
        git clone https://github.com/kovzol/crosswire-sword-mirror
        cd crosswire-sword-mirror
        mkdir build
        cd build
        emcmake cmake ..
        emmake make sword_static
    - name: make-wasm
      run: |
        . emsdk/emsdk_env.sh
        yes | emmake make
    - name: db-full
      run: cd docs/common && make && make svgs
    - name: doc-hu
      run: cd docs/hu && make
