name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: prerequisites
      run: sudo apt update && sudo apt install libsword-common libsword-dev git cmake build-essential libreadline-dev libboost-dev sqlite3 python3 texlive-latex-recommended
    - name: cmake
      run: cmake .
    - name: make
      run: make
    - name: db
      run: cd docs/common && make
